### ISSUE TITLE
undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by xyang35** [jwyang/faster-rcnn.pytorch#190]
I've successfully compiled the cuda dependencies for ROI pooling. Everything looks fine but when I try to call the function RoIPoolFunction(), it comes an error:

ImportError: /home/faster-rcnn.pytorch/lib/model/roi_pooling/_ext/roi_pooling/_roi_pooling.so: undefined symbol: __cudaPopCallConfiguration

Any idea about the problem ? I'm using CUDA 9.2 and pytorch 0.4.

Thanks!

**Comment by xyang35** [comment]
I changed to CUDA 9.0, and it seems that the problem has gone...

**Comment by codewithsk** [comment]
I didn't have any luck moving to cuda 9.0 as well! Anybody else facing the same issue?

**Comment by abhishekcvedia** [comment]
@xyang35  @codewithsk 
Any solutions to this? Changing CUDA version is not helping me.

**Comment by sh8** [comment]
I got the same error when using CUDA9.2.
After changing the version to CUDA8.0, the issue has gone.

**Comment by zhangyuygss** [comment]
I had the same problem when using pytorch0.3.1 with cuda9.2, when I changed to torch0.4.1, the issue fixed.

**Comment by VladVin** [comment]
The answer of @zhangyuygss helped me: PyTorch 0.4.1 + CUDA 9.2 worked.

**Comment by yuqli** [comment]
I use PyTorch 0.4.1 post2 + CUDA 9.2 and it gave the same error.

**Comment by wu-yy** [comment]
I also meet the problem. SO I uninstall the cuda-9.2 and install the cuda-9.0 . I deal with this problem .

**Comment by unclecao** [comment]
Also, when I uninstall the cuda-9.2 and instead install the cuda-9.0, then the problem is fixed. I don't know why

**Comment by Harathi123** [comment]
I got similar issue with CUDA 9.2 + Pytorch 0.4. It got fixed with CUDA 9.0

**Comment by yuqli** [comment]
I used Pytorch + CUDA  8.0 and it worked.

**Comment by BPiepmatz** [comment]
For people with CUDA 9.2 with pytorch 0.4.1: I could solve the issue by installing with conda instead of pip

**Comment by muzammil360** [comment]
I am also facing the same issue. I am using **pytorch '1.0.1.post2'** and cuda92. 
I can't try cuda80 because I can't install it on cluster.

**Comment by Barbarioli** [comment]
Same problem here

**Comment by maxfaine** [comment]
You need to verify that torch version compiled with the correct cuda version.

Please see the following link for help:
https://rusty1s.github.io/pytorch_geometric/build/html/notes/installation.html

**Comment by jshi31** [comment]
I find the root of the problem is the mismatch of the nvcc version and the torchcuda version. You must make sure them to be the same.
Check nvcc version:
`nvcc --version`
Check torch cuda version, go to the python interface and type
`torch.version.cuda`
make sure they are the same and I solved my problem.

**Comment by CodHeK** [comment]
I am facing the same issue!

`nvcc --version -> 9.2`

`torch.version.cuda -> 9.0`

`torch.__version__ -> 0.4.1` 

So I might have to change the nvcc version right? How can install CUDA 9.0 having already installed CUDA 9.2 ?

Thanks!

**Comment by muzammil360** [comment]
Instead of changing cuda version,  Try installing pytorch again.

**Comment by CodHeK** [comment]
What combination of pytorch should I be using instead of 0.4.1?
    On Wednesday, 9 October, 2019, 08:49:39 am IST, muzammil360 <notifications@github.com> wrote:  
 
 Instead of changing cuda version, Try installing pytorch again.

**Comment by Swjtu-only** [comment]
just you run  conda install pytorch=0.4.1 cuda92 -c pytorch
conda install pytorch=0.4.1 cuda(your nvcc-V) -c pytorch

**Comment by 1194949000** [comment]
> I find the root of the problem is the mismatch of the nvcc version and the torchcuda version. You must make sure they are the same.
> Check nvcc version:
> `nvcc --version`
> Check torch cuda version, go to the python interface and type
> `import torch`
> `torch.version.cuda`
> make sure they are the same and I solved my problem.

I changed my CUDA version as you suggested and solved my confusion.Thank you very much!

**Comment by Vio1etovo** [comment]
I change all of it,
nvcc -V ->release 9.0, V9.0.176
torch.version.cuda -> 9.0.176
torch.__version__ ->'0.4.1'
but this changing is not helping me. I don't know why
even I changed gcc5.4 -> 4.8

**Comment by ajithvcoder** [comment]
@Vio1etovo  "Pytorch 0.4.0 is only supported ( it does not support 0.4.1 or higher)" its menitoned in readme. u can try with cuda 8 and torch 0.4.0 .

**Comment by henbucuoshanghai** [comment]
I use cuda 10.0  cudnn10.0 totch1.1    but it still this error


from torch.utils.data.dataloader import numpy_type_map
ImportError: cannot import name 'numpy_type_map'

**Comment by ajithvcoder** [comment]
@henbucuoshanghai change to cuda 8.0 and gcc 5+ and torch 0.4.0 it works

**Comment by henbucuoshanghai** [comment]
but my ubuntu is cuda 10,i have to change it ????when i use 10,and i have to change it back to 10.

**Comment by ajithvcoder** [comment]
you can do it in colab  if you share your email id i can send you the notebook. if you want to do it for cuda 10 , yes you have to either change to code to adapt to cuda 10 or else revert to cuda 8 or cuda9

**Comment by hanhao2019102935** [comment]
> you can do it in colab if you share your email id i can send you the notebook. if you want to do it for cuda 10 , yes you have to either change to code to adapt to cuda 10 or else revert to cuda 8 or  cuda9
I tried to experiment this project on CoLab, but it failed because of CUDA. Could you please send me your Notebook?My email address is 178337111@qq.com.My VX: H178337111.Looking forward to your reply

**Comment by ajithvcoder** [comment]
@hanhao2019102935  i dont have notebook it has been a long time but for chaning cuda versions you can refer this .https://forums.developer.nvidia.com/t/install-cuda-8-0-on-google-colab/112482

**Comment by hanhao2019102935** [comment]
@ajithvallabai First of all, thank you for telling me about the installation of CUDA.But when I implemented this code on coLab.I installed Torch0.4.0 successfully, but when I used print(torch.__version__) I found that the Torch0.4.0 version had not changed.I installed Cuda9.0 Python 3.6, but the Torch issue never resolved

**Comment by hanhao2019102935** [comment]
@ajithvallabai I think I know my problem. Now the Python version of coLab is 3.7. Python 3.7 will not run this code.I tried to use Conda to modify the Python version to 3.6, but apparently I only saw superficial changes when I tried to install a torch for 3.6, and it failed.Now I have no way to run it on coLab.

**Comment by onkarkris** [comment]
> torch.version.cuda
 I have 
torch.version.cuda
'9.0.176'

and nvcc --version 
Cuda compilation tools, release 9.0, V9.0.176

but still error persist ImportError: lib/model/nms/_ext/nms/_nms.so: undefined symbol: __cudaPopCallConfiguration
