### ISSUE TITLE
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1532584813488/work/aten/src/THC/THCGeneral.cpp:74

### ISSUE THREAD

**Issue by guohaoyuan** [jwyang/faster-rcnn.pytorch#377]
Thank you for this code, it's amazing!  I've been learning about your project recently, but this error occurred at the beginning of the training. I thought the graphics card didn't match the driver. After trying it out, I found that it wasn't.
##################################################
Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
voc_2007_trainval gt roidb loaded from /home/ghy/faster-rcnn.pytorch-master/data/cache/voc_2007_trainval_gt_roidb.pkl
done
Preparing training data...
done
******************************************************
before filtering, there are 10022 images...
after filtering, there are 10022 images...
10022 roidb entries
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1532584813488/work/aten/src/THC/THCGeneral.cpp line=74 error=38 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "trainval_net.py", line 222, in <module>
    im_data = im_data.cuda()
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1532584813488/work/aten/src/THC/THCGeneral.cpp:74

###############################################
Does anyone know how to solve it?

**Comment by guohaoyuan** [comment]
It has been solved. Reasons for not calling CUDA!

**Comment by yaelbrumer** [comment]
Hi, I'm still seeing the same error. What was the solution for that?

**Comment by niuniu111** [comment]
> Thank you for this code, it's amazing! I've been learning about your project recently, but this error occurred at the beginning of the training. I thought the graphics card didn't match the driver. After trying it out, I found that it wasn't.
> ##################################################
> Loaded dataset `voc_2007_trainval` for training
> Set proposal method: gt
> Appending horizontally-flipped training examples...
> voc_2007_trainval gt roidb loaded from /home/ghy/faster-rcnn.pytorch-master/data/cache/voc_2007_trainval_gt_roidb.pkl
> done
> Preparing training data...
> done
> 
> before filtering, there are 10022 images...
> after filtering, there are 10022 images...
> 10022 roidb entries
> THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1532584813488/work/aten/src/THC/THCGeneral.cpp line=74 error=38 : no CUDA-capable device is detected
> Traceback (most recent call last):
> File "trainval_net.py", line 222, in
> im_data = im_data.cuda()
> RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1532584813488/work/aten/src/THC/THCGeneral.cpp:74
> 
> ###############################################
> Does anyone know how to solve it?

how do you solve it?

**Comment by guohaoyuan** [comment]
> Hi, I'm still seeing the same error. What was the solution for that?
我的原因在：命令行需要修改GPU的参数，即，调用哪个GPU

**Comment by duygusar** [comment]
@guohaoyuan 

I have the same problem, can you please explain how you solved it??

**Comment by kangkang59812** [comment]
@guohaoyuan --cuda cuda:0 ?

**Comment by gmt710** [comment]
One possible solution is to put the following two statements at **the front** of the code.
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = '0'
```

**Comment by zzu0654** [comment]
I'm still seeing the same error.

**Comment by ShaheenPerveen** [comment]
Hi
I am also encountering similar issue,
even after trying all the above solves. 
@zzu0654 were you able to solve it?

**Comment by ahtsham58** [comment]
Also getting the same error. My GPU is cross-verified and its active.

you can see the last thread here. https://github.com/rusty1s/pytorch_geometric/issues/2489
